(() => {
'use strict';
const C=window.LOVE_CONFIG,F=C.platform,E=window.LovePlatform,$=s=>document.querySelector(s),KEY='love-platform-v2';
const clean=()=>({level:0,checkpoint:65,hearts:0,collected:[],letters:[],bridge:false,finished:false,sisterPassed:false,sisterHearts:0,policePermit:false,policePassed:false,benoniKeys:[],benoniPassed:false,eggs:[]});
let saved;try{saved={...clean(),...JSON.parse(localStorage.getItem(KEY)||'{}')};}catch{saved=clean();}
saved.level=Math.max(0,Math.min(2,Number(saved.level)||0));if(!Array.isArray(saved.collected))saved.collected=[];if(!Array.isArray(saved.letters))saved.letters=[];if(!Array.isArray(saved.benoniKeys))saved.benoniKeys=[];
let canvasObserver,lastUpdate='';
let world,player,canvas,g,W=960,H=540,camera=0,time=0,paused=true,last=0,frame=0,particles=[],toastTimer,runId=0,nearLetter=null,boostUntil=0,sisterToastAt=-10,policeToastAt=-10,benoniToastAt=-10;
const input={left:false,right:false,jump:false,peace:false,unlock:false},heldKeys=new Set(),touches={left:new Set(),right:new Set()},images={};
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
// The supplied character sheets are adapted into four-pose transparent atlases.
const sprites={},spriteURLs={},poseIndex={smiling:0,thinking:0,normal:0,run1:1,run2:2,celebrating:3,'holding-heart':3,peace:3};
function refreshPortraits(){document.querySelectorAll('[data-character]').forEach(el=>{const url=spriteURLs[el.dataset.character+el.dataset.pose];if(url)el.src=url;});}
for(const person of ['bongeka','bongumusa','gcinile']){const atlas=new Image();atlas.onload=()=>{const cw=Math.floor(atlas.naturalWidth/2),ch=Math.floor(atlas.naturalHeight/2);sprites[person]=[];for(let i=0;i<4;i++){const frame=document.createElement('canvas');frame.width=cw;frame.height=ch;const ctx=frame.getContext('2d');ctx.drawImage(atlas,(i%2)*cw,Math.floor(i/2)*ch,cw,ch,0,0,cw,ch);const pixels=ctx.getImageData(0,0,cw,ch).data;let left=cw,top=ch,right=0,bottom=0;for(let y=0;y<ch;y++)for(let x=0;x<cw;x++)if(pixels[(y*cw+x)*4+3]>80){left=Math.min(left,x);right=Math.max(right,x);top=Math.min(top,y);bottom=Math.max(bottom,y);}const cut=document.createElement('canvas');cut.width=right-left+1;cut.height=bottom-top+1;cut.getContext('2d').drawImage(frame,left,top,cut.width,cut.height,0,0,cut.width,cut.height);sprites[person].push(cut);for(const [pose,index]of Object.entries(poseIndex))if(index===i)spriteURLs[person+pose]=cut.toDataURL();}refreshPortraits();};atlas.src='assets/characters/pixel/'+person+'.png';}
function save(){try{localStorage.setItem(KEY,JSON.stringify(saved));}catch{}}
function toast(t){if(canvas?.isConnected){lastUpdate=t;$('#hint').textContent='CLUE \u2022';$('#hint').setAttribute('aria-label','Read clue and latest quest update');return;}$('#toast').innerHTML='<span class="event-label">QUEST UPDATE</span>'+esc(t);$('#toast').classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').classList.remove('show'),3300);}
function release(){heldKeys.clear();touches.left.clear();touches.right.clear();input.left=input.right=input.jump=input.peace=input.unlock=false;document.querySelectorAll('.control').forEach(b=>b.classList.remove('held'));}
function stop(){canvasObserver?.disconnect();runId++;cancelAnimationFrame(frame);release();}
function portrait(person,pose='smiling'){return `<img data-character="${person}" data-pose="${pose}" src="${esc(spriteURLs[person+pose]||C.characters[person]+pose+'.svg')}" alt="${esc(person==='bongeka'?C.girlfriendName:C.boyfriendName)}">`;}
function missionCard(index,button,buttonID='ready'){
 const m=F.missions[index],face=index===1?`<img class="portrait" src="${esc(F.police.asset)}" alt="${esc(F.police.name)}">`:portrait('bongumusa').replace('<img','<img class="portrait"');return `<div class="mission-card"><span class="quest-badge">${esc(m.title)}</span><h2>${esc(m.objective)}</h2><div class="dialogue-row">${face}<div><span class="speaker-tag">${esc(m.speaker)}</span><p>${esc(m.message)}</p></div></div><div class="quest-objective"><span>${esc(m.icon)}</span>${esc(m.tip)}</div><div class="quest-reward">REWARD: ${esc(m.reward)}</div><div class="key-guide"><span><kbd>← →</kbd> MOVE</span><span><kbd>JUMP ×2</kbd> DOUBLE JUMP</span></div>${button?`<button class="primary" id="${buttonID}">${esc(button)}</button>`:''}</div>`;
}
function previewMission(i){$('#modal-body').innerHTML=missionCard(i,'');refreshPortraits();$('#modal').showModal();}
function showHelp(){tone('menu');$('#modal-body').innerHTML=`<span class="quest-badge">${esc(F.gameUI.how)}</span><h2>${esc(F.gameUI.helpTitle)}</h2><p class="quest-help">${esc(F.gameUI.help)}</p><div class="mission-tip">${esc(F.missions[0].tip)}</div>`;refreshPortraits();$('#modal').showModal();}
function home(){stop();canvas=null;$('#app').classList.remove('playing');const U=F.gameUI,hasSave=saved.checkpoint>65||saved.level>0||saved.hearts>0;const title=U.title.split(' ');$('#app').innerHTML=`<section class="title-screen" aria-label="Game title screen"><div class="title-logo"><span class="edition">${esc(U.mission)}</span><span class="name">${esc(C.girlfriendName.toUpperCase())}’S</span><h1>${esc(title[0])}<br><span>${esc(title.slice(1).join(' '))}</span></h1><p class="tagline">${esc(U.tagline)}</p></div><div class="title-hero">${portrait('bongeka','celebrating').replace('<img','<img class="bongeka"')}${portrait('bongumusa','holding-heart').replace('<img','<img class="bongumusa"')}<span class="hero-heart" aria-hidden="true">♥</span><span class="player-tag">PLAYER 01 · ${esc(C.girlfriendName.toUpperCase())}</span></div><div class="title-menu"><div class="menu-top"><span>SAVE SLOT 01</span><i>${saved.finished?'COMPLETE':hasSave?'SAVED':'READY'}</i></div><button class="primary" id="start">▶ ${esc(saved.finished?U.reunion:hasSave?U.continueGame:U.newGame)}</button><div class="menu-actions"><button class="subtle" id="how">${esc(U.how)}</button><button class="subtle" id="fresh-start">${esc(U.fresh)}</button></div><div class="save-slot">${portrait('bongeka')}<div><strong>${esc(F.missions[saved.level].short)} · ${saved.hearts} ♥</strong><span>${saved.finished?'You found your person.':hasSave?'Your checkpoint is waiting.':'One quest. Unlimited chances.'}</span></div></div></div></section><section class="home-radio"><div class="radio-face">${portrait('bongumusa')}</div><div><span class="speaker">${esc(U.radio)}</span><p>${esc(U.brief)}</p></div></section><section class="map-panel"><div class="map-heading"><h2>${esc(U.mapTitle)}</h2><p>${esc(U.mapSub)}</p></div><div class="route-map">${F.missions.map((m,i)=>`<button id="route-${i}" class="map-node ${saved.finished||i<saved.level?'done':i===saved.level?'current':''}" aria-label="Preview mission ${i+1}: ${esc(m.short)}"><span>${esc(m.icon)}</span>${esc(m.short)}<small>${saved.finished||i<saved.level?'✓ CLEARED':i===saved.level?'YOU ARE HERE':'SCOUT AHEAD'}</small></button>`).join('')}</div></section><div class="title-footer"><span>BUILT FOR ${esc(C.girlfriendName.toUpperCase())}. BY HER FAVOURITE PERSON. ♥</span><a href="classic.html">BONUS: THE ORIGINAL CHALLENGES ↗</a></div>`;
 refreshPortraits();$('#start').onclick=()=>{tone('menu');saved.finished?ending():startLevel();};$('#how').onclick=showHelp;for(let i=0;i<3;i++)$('#route-'+i).onclick=()=>{tone('menu');previewMission(i);};$('#fresh-start').onclick=()=>{if(confirm(U.freshConfirm)){saved=clean();save();tone('menu');startLevel();}};
}
function startLevel(){stop();lastUpdate='';$('#toast').classList.remove('show');clearTimeout(toastTimer);$('#app').classList.add('playing');world=E.world(saved.level);if(world.sister){world.sister.passed=saved.sisterPassed||saved.checkpoint>615;world.sister.hits=Math.min(3,Math.max(0,Number(saved.sisterHearts)||0));}if(world.police){world.police.permit=saved.policePermit;world.police.passed=saved.policePassed||saved.checkpoint>world.police.x+world.police.w;}if(world.benoni){world.benoni.passed=saved.benoniPassed||saved.checkpoint>world.benoni.gate;for(const k of world.benoni.keys)k.collected=saved.benoniKeys.includes(k.id);}sisterToastAt=policeToastAt=benoniToastAt=-10;saved.checkpoint=Math.max(65,Math.min(world.goal-100,Number(saved.checkpoint)||65));player=E.player(saved.checkpoint,world.ground-76);particles=[];time=0;camera=0;boostUntil=0;nearLetter=null;
$('#app').innerHTML=`<div class="route-banner">${esc(F.journey.from)} <span>→</span> ${esc(F.journey.to)} <small>QUEST ${saved.level+1} / 3 · SAVE SLOT 01</small></div><div class="hud"><div class="hud-title"><span>WORLD ${saved.level+1} · ${esc(C.girlfriendName.toUpperCase())}</span><strong>${esc(F.missions[saved.level].short)}</strong></div><div class="hud-stat" id="heart-count">♥ ${saved.hearts}</div><div class="hud-stat" id="distance">0%</div><button id="pause" aria-label="Pause game">Ⅱ PAUSE</button></div><div class="challenge-bar" id="challenge" role="status"></div><div class="game-frame"><canvas id="game" tabindex="0" aria-label="Platform game. Left and right arrows or A and D move. Space, W or Up jumps. Jump twice for a double jump. E reads notes or unlocks the escape gate. P offers peace."></canvas><div class="overlay" id="overlay">${missionCard(saved.level,'LET’S GO →')}</div></div><div class="control-dock"><div class="action-row"><button class="subtle peace-control" id="peace" hidden>${esc(F.sister.button)}</button><button class="subtle escape-control" id="unlock" hidden>${esc(F.benoni.button)}</button><button class="subtle" id="read" hidden>READ NOTE ?</button><button class="subtle" id="hint">CLUE ?</button><button class="subtle" id="home">SAVE & EXIT</button></div><div class="controls"><div class="direction"><button class="control" data-move="left" aria-label="Move left">\u25c0</button><button class="control" data-move="right" aria-label="Move right">\u25b6</button></div><button class="control jump" id="jump" aria-label="Jump or double jump">JUMP \u219f</button></div></div><div class="game-note"><div class="hint-radio"><div class="radio-face">${portrait('bongumusa')}</div><div><span class="speaker">${esc(F.gameUI.radio)}</span><span id="instruction">${esc(F.gameUI.defaultTip)}</span></div></div></div><div class="chapters">${F.worlds.map((_,i)=>`<div class="chapter ${i<saved.level?'done':i===saved.level?'current':''}" aria-label="World ${i+1}"></div>`).join('')}</div>`;
refreshPortraits();canvas=$('#game');g=canvas.getContext('2d');resize();if(window.ResizeObserver){canvasObserver=new window.ResizeObserver(resize);canvasObserver.observe(canvas);}$('#hint').onclick=()=>{paused=true;release();$('#modal-body').innerHTML='<span class="quest-badge">RADIO CLUE</span><h2>Your next move</h2><p>'+esc($('#instruction').textContent)+'</p>'+(lastUpdate?'<div class="mission-tip">'+esc(lastUpdate)+'</div>':'');$('#hint').textContent='CLUE ?';refreshPortraits();$('#modal').showModal();};paused=true;$('#ready').onclick=resume;$('#pause').onclick=()=>paused?resume():pause();$('#home').onclick=()=>{save();home();};$('#read').onclick=readLetter;$('#unlock').onclick=()=>{if(!paused){input.unlock=true;canvas.focus({preventScroll:true});}};$('#peace').onclick=()=>{if(!paused){input.peace=true;canvas.focus({preventScroll:true});}};
for(const b of document.querySelectorAll('[data-move]')){const dir=b.dataset.move;b.onpointerdown=e=>{e.preventDefault();b.setPointerCapture(e.pointerId);touches[dir].add(e.pointerId);b.classList.add('held');syncInput();};const up=e=>{touches[dir].delete(e.pointerId);if(!touches[dir].size)b.classList.remove('held');syncInput();};b.onpointerup=up;b.onpointercancel=up;b.onlostpointercapture=up;}
$('#jump').onpointerdown=e=>{e.preventDefault();if(!paused)input.jump=true;};$('#jump').onclick=e=>{if(e.detail===0&&!paused)input.jump=true;};const id=runId;last=performance.now();function loop(t){if(id!==runId)return;const dt=Math.min(.025,(t-last)/1000);last=t;if(!paused){time+=dt;update(dt);}draw();frame=requestAnimationFrame(loop);}frame=requestAnimationFrame(loop);}
function resize(){if(!canvas?.isConnected)return;const r=canvas.getBoundingClientRect();if(!r.width||!r.height)return;H=540;W=Math.max(500,H*r.width/r.height);const d=Math.min(2,window.devicePixelRatio||1);canvas.width=Math.round(W*d);canvas.height=Math.round(H*d);g.setTransform(d,0,0,d,0,0);}
function resume(){if(!canvas?.isConnected)return;paused=false;$('#overlay').hidden=true;$('#pause').textContent='Ⅱ PAUSE';canvas.focus({preventScroll:true});release();}
function pause(){if(!canvas?.isConnected)return;paused=true;release();$('#pause').textContent='▶ RESUME';$('#overlay').innerHTML=`<div class="mission-card"><span class="quest-badge">${esc(F.gameUI.pauseTitle)}</span><h2>${esc(F.gameUI.pauseTitle)}</h2><div class="dialogue-row">${portrait('bongumusa','thinking').replace('<img','<img class="portrait"')}<div><span class="speaker-tag">${esc(C.boyfriendName)}</span><p>${esc(F.gameUI.pauseMessage)}</p></div></div><br><button class="primary" id="resume">${esc(F.gameUI.resume)}</button></div>`;refreshPortraits();$('#overlay').hidden=false;$('#resume').onclick=()=>{tone('menu');resume();};}
function syncInput(){input.left=heldKeys.has('ArrowLeft')||heldKeys.has('a')||touches.left.size>0;input.right=heldKeys.has('ArrowRight')||heldKeys.has('d')||touches.right.size>0;}
function respawn(){world.projectiles=[];if(world.benoni){world.benoni.alert=0;world.benoni.villain.x=1010;}const x=saved.checkpoint;player=E.player(x,384);player.invincible=2;burst(x+20,420,15);toast(world.benoni&&!world.benoni.passed?F.benoni.caught:F.retry);}
function update(dt){const events=E.step(player,world,input,dt,time,saved.bridge);input.jump=input.peace=input.unlock=false;for(const event of events){if(event==='benoni-key'){tone('secret');saved.benoniKeys=world.benoni.keys.filter(k=>k.collected).map(k=>k.id);save();burst(player.x,player.y,15);toast(F.benoni.key);}if(event==='benoni-pass'){saved.benoniPassed=true;save();burst(player.x,player.y,30);toast(F.benoni.passed);}if(event==='benoni-alert'&&time-benoniToastAt>3){benoniToastAt=time;toast(F.benoni.alert);}if(event==='benoni-locked'&&time-benoniToastAt>1){benoniToastAt=time;toast(F.benoni.locked);}if(event==='sister-blocked'&&time-sisterToastAt>3){sisterToastAt=time;toast(F.sister.blocked);}if(event==='sister-heart'){tone('coin');saved.sisterHearts=world.sister.hits;save();burst(world.sister.x,380,12);toast(F.sister.hit);}if(event==='sister-wait'&&time-sisterToastAt>1){sisterToastAt=time;toast(F.sister.wait);}if(event==='police-permit'){saved.policePermit=true;save();toast(F.police.permit);}if(event==='police-pass'){tone('secret');saved.policePassed=true;save();toast(F.police.passed);}if(event==='police-stop'&&time-policeToastAt>4){policeToastAt=time;toast(F.police.stop);}if(event==='sister-peace'){saved.sisterPassed=true;save();burst(world.sister.x+20,380,22);toast(F.sister.peace);}if(event==='hurt'&&time<boostUntil)continue;if(event==='fall'||event==='hurt'){respawn();break;}if(event==='stomp'){burst(player.x,player.y+76,12);toast(F.gameUI.stomp);tone('pop');}if(event==='jump'){burst(player.x+20,player.y+65,5);tone('jump');}}
for(const h of world.hearts){const id=saved.level+':'+h.id;if(!saved.collected.includes(id)&&E.overlap(player,h)){saved.collected.push(id);saved.hearts++;burst(h.x,h.y,8);particles.push({x:h.x,y:h.y,vx:0,vy:-45,life:1.1,color:'#fff1be',label:'+1 ♥'});tone('coin');if(saved.hearts%8===0){boostUntil=time+6;player.invincible=6;toast(F.power);}save();}}
for(const cp of world.checkpoints){if(player.x>=cp.x&&cp.x>saved.checkpoint&&player.grounded){saved.checkpoint=cp.x;save();burst(cp.x,420,16);toast(F.checkpoint);}}
if(!saved.bridge&&E.overlap(player,world.switch)){saved.bridge=true;save();burst(world.switch.x,430,25);toast(F.bridge);}
const nearSister=world.sister&&!world.sister.passed&&Math.abs(player.x-world.sister.x)<180;$('#peace').hidden=!nearSister;$('#peace').textContent=F.sister.button+' '+(world.sister?world.sister.hits:0)+'/3';const nearPolice=world.police&&!world.police.passed&&Math.abs(player.x-world.police.x)<260;const b=world.benoni;const inBenoni=b&&!b.passed&&player.x>b.start-70&&player.x<b.end;$('#unlock').hidden=!b||b.passed||Math.abs(player.x-b.gate)>115;const challenge=$('#challenge');challenge.hidden=false;if(!nearSister&&!nearPolice&&!inBenoni){challenge.textContent=F.missions[saved.level].objective;challenge.className='challenge-bar';}if(nearSister){challenge.textContent=F.sister.title+' | '+world.sister.hits+'/3 | '+(world.sister.calm?F.sister.calm:F.sister.attack)+' ('+Math.ceil(world.sister.remaining||0)+'s)';challenge.className='challenge-bar '+(world.sister.calm?'calm':'danger');}else if(nearPolice){challenge.textContent=F.police.title+' | '+(!world.police.permit?F.police.missing:world.police.green?F.police.green:F.police.red)+' ('+Math.ceil(world.police.remaining||0)+'s)';challenge.className='challenge-bar '+(world.police.green&&world.police.permit?'calm':'danger');}else if(inBenoni){const message=F.benoni.title+' | '+F.benoni.keys+' '+b.keys.filter(k=>k.collected).length+'/3 | '+(b.hidden?F.benoni.hidden:b.alert>0?F.benoni.chase:F.benoni.search);if(challenge.textContent!==message)challenge.textContent=message;challenge.className='challenge-bar '+(b.hidden?'calm':'danger');}nearLetter=world.letters.find(l=>Math.abs(player.x-l.x)<85&&Math.abs(player.y-l.y)<100)||null;$('#read').hidden=!nearLetter;$('#instruction').textContent=nearSister?F.sister.hint:nearPolice?F.police.hint:inBenoni?F.benoni.hint:nearLetter?F.gameUI.letterTip:time<boostUntil?F.gameUI.shieldTip:F.gameUI.defaultTip;
$('#heart-count').textContent='♥ '+saved.hearts;$('#distance').textContent=Math.min(100,Math.floor(player.x/world.goal*100))+'%';
particles=particles.filter(p=>{p.life-=dt;p.x+=p.vx*dt;p.y+=p.vy*dt;p.vy+=200*dt;return p.life>0;});if(player.x>=world.goal-45)complete();}
function burst(x,y,n){if(matchMedia('(prefers-reduced-motion: reduce)').matches)n=3;for(let i=0;i<n;i++)particles.push({x,y,vx:(Math.random()-.5)*160,vy:-80-Math.random()*180,life:1.4,color:['#d87992','#f3ce71','#fff6db'][i%3]});}
function readLetter(){if(!nearLetter)return;const l=C.loveLetters[nearLetter.id],id=saved.level+':'+nearLetter.id;if(!saved.letters.includes(id)){saved.letters.push(id);save();}tone('secret');paused=true;release();$('#modal-body').innerHTML=`<span class="quest-badge">${esc(F.gameUI.letter)}</span><h2>${esc(l.title)}</h2><div class="dialogue-row">${portrait('bongumusa','holding-heart').replace('<img','<img class="portrait"')}<div><span class="speaker-tag">${esc(C.boyfriendName)}</span><p>FOR ${esc(C.girlfriendName.toUpperCase())}. OPEN WHEN YOU NEED ME.</p></div></div><p class="letter-copy">${esc(l.message)}</p>`;refreshPortraits();$('#modal').showModal();}
$('#modal-close').onclick=()=>$('#modal').close();$('#modal').addEventListener('close',()=>{if(canvas?.isConnected)resume();});
function complete(){paused=true;release();tone('win');if(saved.level===2){saved.finished=true;save();ending();return;}$('#overlay').innerHTML=`<div class="mission-card"><span class="quest-badge">WORLD ${saved.level+1} · ${esc(F.gameUI.worldClear)}</span><h2>${esc(F.gameUI.worldClear)}</h2><div class="dialogue-row">${portrait('bongeka','celebrating').replace('<img','<img class="portrait"')}<div><span class="speaker-tag">${esc(C.boyfriendName)}</span><p>${esc(F.worlds[saved.level].message)}</p><div class="quest-reward">UNLOCKED: ${esc(F.missions[saved.level].reward)}</div></div></div><div class="quest-objective"><span>♥</span>${saved.hearts} HEARTS · ${saved.letters.length} NOTES FOUND</div><button class="primary" id="next-world">NEXT: ${esc(F.missions[saved.level+1].short)} →</button></div>`;$('#overlay').hidden=false;$('#next-world').onclick=()=>{tone('menu');saved.level++;saved.checkpoint=65;saved.bridge=false;save();startLevel();};}
function heart(x,y,size,color){g.save();g.translate(x,y);g.scale(size/30,size/30);g.fillStyle=color;g.beginPath();g.moveTo(0,8);g.bezierCurveTo(-28,-9,-12,-24,0,-10);g.bezierCurveTo(12,-24,28,-9,0,8);g.fill();g.restore();}
function round(x,y,w,h,r,color){g.fillStyle=color;g.beginPath();g.roundRect(x,y,w,h,r);g.fill();}
function text(t,x,y,size=14,color='#685050',align='left'){g.fillStyle=color;g.font=`bold ${size}px Trebuchet MS, sans-serif`;g.textAlign=align;g.fillText(t,x,y);g.textAlign='left';}
function cloud(x,y,s=1,color='#fff8ed'){g.fillStyle=color;g.beginPath();g.ellipse(x,y,45*s,17*s,0,0,Math.PI*2);g.ellipse(x-16*s,y-14*s,20*s,20*s,0,0,Math.PI*2);g.ellipse(x+14*s,y-20*s,25*s,24*s,0,0,Math.PI*2);g.fill();}
function drawCharacter(person,pose,x,y,w=54,h=87,face=1){const im=sprites[person]?.[poseIndex[pose]||0];if(!im)return;g.save();g.imageSmoothingEnabled=false;const scale=h/im.height,dw=im.width*scale;if(face<0){g.translate(x+w,y);g.scale(-1,1);x=0;y=0;}g.drawImage(im,x+(w-dw)/2,y,dw,h);g.restore();}
function drawBenoni(foreground=false){
const b=world.benoni;if(!b)return;
g.save();g.beginPath();g.rect(b.start,0,b.end-b.start,540);g.clip();
if(!foreground){const night=g.createLinearGradient(0,0,0,540);night.addColorStop(0,'#222c43');night.addColorStop(1,'#5c526d');g.fillStyle=night;g.fillRect(b.start,0,b.end-b.start,540);
for(let x=b.start+20;x<b.end;x+=110){round(x,245+(x%3)*25,83,215,3,'#33394e');for(let j=0;j<3;j++)round(x+12+j*21,285,9,16,1,'#b38b75');}
cloud(610,215,2,'#b1a3ba18');text(F.benoni.title.toUpperCase(),700,95,26,'#ead7df','center');text(F.benoni.fiction,700,119,12,'#cab4c5','center');
}else{for(const lamp of b.shelters){g.fillStyle='#ffe7aa25';g.beginPath();g.ellipse(lamp,393,45,74,0,0,7);g.fill();round(lamp-3,300,6,160,2,'#9b9091');round(lamp-13,289,26,15,6,'#ffe6a7');text('SAFE',lamp,480,11,'#fbe1a5','center');}
if(!b.passed){for(const beam of b.beams){g.fillStyle=b.alert>0?'#ee8eab35':'#e4e1ca28';g.beginPath();g.moveTo(beam.base,180);g.lineTo(beam.x-30,460);g.lineTo(beam.x+30,460);g.fill();round(beam.base-12,169,24,14,4,'#b7a9ab');}
const v=b.villain;g.fillStyle='#232338';g.beginPath();g.moveTo(v.x+21,v.y+12);g.lineTo(v.x-5,v.y+82);g.lineTo(v.x+48,v.y+82);g.fill();g.beginPath();g.ellipse(v.x+21,v.y+18,19,25,0,0,7);g.fill();g.fillStyle='#dccbd1';g.beginPath();g.ellipse(v.x+21,v.y+20,11,16,0,0,7);g.fill();round(v.x+13,v.y+15,5,6,2,'#49323e');round(v.x+23,v.y+15,5,6,2,'#49323e');text(F.benoni.villain,v.x+21,v.y-10,11,'#dfb8c9','center');
round(b.gate,0,8,460,2,'#8e829b');for(let y=50;y<460;y+=70){round(b.gate-12,y,32,15,3,'#c59baf');text('LOCK',b.gate+4,y+12,9,'#392d45','center');}}
for(const k of b.keys)if(!k.collected){g.strokeStyle='#ffdda2';g.lineWidth=4;g.beginPath();g.arc(k.x+10,k.y+9,7,0,7);g.moveTo(k.x+16,k.y+15);g.lineTo(k.x+25,k.y+25);g.lineTo(k.x+29,k.y+21);g.stroke();text(String(k.id+1),k.x+10,k.y-7,12,'#ffdda2','center');}
text(F.benoni.gate,b.gate-15,158,12,'#f6d7df','right');}g.restore();
}
function draw(){if(!g||!world)return;const theme=F.worlds[saved.level],grad=g.createLinearGradient(0,0,0,H);grad.addColorStop(0,theme.sky[0]);grad.addColorStop(1,theme.sky[1]);g.fillStyle=grad;g.fillRect(0,0,W,H);camera=Math.max(0,Math.min(world.length-W,player.x-W*.33));
if(saved.level===1){g.fillStyle='#fff4cd';g.beginPath();g.arc(W-110,83,38,0,7);g.fill();for(let i=0;i<25;i++)text('✦',((i*137-camera*.15)%(W+100)+W+100)%(W+100),30+(i*59)%220,9,'#efd7d5');}else{g.fillStyle='#f7d48b';g.beginPath();g.arc(W-110,93,42,0,7);g.fill();}
for(let i=0;i<8;i++){const x=i*280-camera*.22;cloud(x,90+(i%3)*34,.7,'#fff7edb0');}
if(theme.scene==='hills'){for(let i=-1;i<10;i++){const x=i*330-camera*.2;g.fillStyle=i%2?'#97b3a1':'#a7c1ae';g.beginPath();g.moveTo(x-70,440);g.lineTo(x+120,155+(i%3)*32);g.lineTo(x+360,440);g.fill();}}if(theme.scene==='city'){for(let i=-1;i<12;i++){const x=i*115-camera*.25,height=100+((i+12)*73)%180;round(x,460-height,88,height,3,i%2?'#aa8899':'#b79da7');for(let row=0;row<height-20;row+=24)for(let col=0;col<3;col++)round(x+12+col*24,470-height+row,8,12,1,'#f7dfaa');}const tx=world.goal-310-camera*.4;round(tx,145,12,315,2,'#877687');round(tx-24,190,60,26,8,'#a38b9b');round(tx-14,165,40,22,7,'#ba9aac');}for(let i=-1;i<12;i++){const x=i*420-camera*.35;g.fillStyle=theme.hill;g.beginPath();g.ellipse(x+200,480,300,190+(i%2)*50,0,Math.PI,Math.PI*2);g.fill();}
g.save();g.translate(-camera,0);drawBenoni();text(theme.place,130,240,24,saved.level===1?'#efded4':'#7b8270');
for(let i=0;i<world.length;i+=190){const night=theme.scene==='road';if(night){round(i,355-(i%3)*15,110,120,3,'#615978');for(let j=0;j<4;j++)round(i+12+j*23,385,12,20,2,'#e8c692');}else{g.strokeStyle='#8d8064';g.lineWidth=7;g.beginPath();g.moveTo(i+60,460);g.lineTo(i+60,320);g.stroke();cloud(i+60,320,1.2,theme.scene==='city'?'#bfa1cc':theme.hill);if(theme.scene==='city'){for(let j=0;j<5;j++)text('·',i+20+j*17,330+j%2*11,26,'#e6bbdc');}}}
if(theme.scene==='road'){round(180,388,125,59,10,'#daabb8');round(195,398,62,20,4,'#514e6d');round(265,399,26,35,4,'#514e6d');for(const wx of [203,280]){g.fillStyle='#484354';g.beginPath();g.arc(wx,449,12,0,7);g.fill();}text('LOVE EXPRESS',242,385,11,'#fce6cf','center');round(1080,254,10,206,3,'#bca6b2');round(1340,254,10,206,3,'#bca6b2');round(1070,246,290,47,8,'#e4c4b7');text(F.journey.via.toUpperCase(),1215,275,18,'#775a65','center');}for(const [x,w]of world.gaps){round(x,485,w,80,5,saved.level===1?'#69547e':'#b2cdd0');for(let j=0;j<4;j++)text('~',x+15+j*30,515+Math.sin(time*2+j)*3,25,'#fff2d8');}
for(const p of saved.bridge?world.platforms.concat(world.bridge):world.platforms){round(p.x,p.y,p.w,p.h,p.ground?3:8,p.bridge?'#d1969d':theme.soil);round(p.x,p.y,p.w,9,4,p.moving?'#f2c577':p.bridge?'#f0bcc0':theme.grass);if(p.ground){for(let x=p.x+15;x<p.x+p.w;x+=42){text('·',x,p.y+34,22,'#ead3af');}}else if(p.moving)text('♡',p.x+p.w/2,p.y+17,13,'#fff7db','center');}
for(const h of world.hearts)if(!saved.collected.includes(saved.level+':'+h.id))heart(h.x+13,h.y+15+Math.sin(time*3+h.x)*4,23,'#cf6686');
for(const cp of world.checkpoints){g.strokeStyle='#819865';g.lineWidth=4;g.beginPath();g.moveTo(cp.x+16,460);g.lineTo(cp.x+16,414);g.stroke();heart(cp.x+16,411,30,cp.x<=saved.checkpoint?'#c96285':'#ecafba');}
const sw=world.switch;round(sw.x,sw.y,sw.w,sw.h,8,saved.bridge?'#a4b57d':'#e6acb6');heart(sw.x+19,sw.y+19,20,'#fff4e4');text(saved.bridge?'LOVE BRIDGE':'♥ SWITCH',sw.x+19,sw.y-12,11,saved.level===1?'#f7e2d2':'#76524f','center');
for(const l of world.letters){const read=saved.letters.includes(saved.level+':'+l.id);round(l.x-5,l.y-9+Math.sin(time*2)*3,34,25,4,read?'#d4c1a7':'#fff6df');text('✉',l.x+12,l.y+12+Math.sin(time*2)*3,23,'#b7637a','center');}
for(const h of world.hazards){if(h.kind==='puddle'){g.fillStyle='#77859b';g.beginPath();g.ellipse(h.x+h.w/2,455,h.w/2,8,0,0,7);g.fill();text('~',h.x+h.w/2,457,15,'#d9e8e1','center');}else{g.fillStyle=h.kind==='thorns'?'#8c617c':'#e4a271';for(let x=h.x;x<h.x+h.w;x+=14){g.beginPath();g.moveTo(x,h.y+h.h);g.lineTo(x+7,h.y);g.lineTo(x+14,h.y+h.h);g.fill();}if(h.kind==='cone')round(h.x,h.y+18,h.w,5,1,'#fff3dc');}}for(const b of world.projectiles){round(b.x,b.y,b.w,b.h,8,'#ba5d87');text('BEEF',b.x+b.w/2,b.y+17,10,'#fff7e9','center');}if(world.police){const o=world.police;if(!o.permit){round(o.card.x,o.card.y,o.card.w,o.card.h,5,'#f5b7c7');heart(o.card.x+16,o.card.y+17,17,'#fff7e6');text('PASSPORT',o.card.x+16,o.card.y-12,10,'#ffe5d7','center');}round(o.x+57,407,15,53,2,'#9b9caa');round(o.x+51,360,27,52,6,'#3f455c');g.fillStyle=o.green||o.passed?'#a8d6a8':'#ef9d9d';g.beginPath();g.arc(o.x+64,o.green||o.passed?396:375,8,0,7);g.fill();if(!o.passed){round(o.x,385,6,75,1,'#d1c0a7');if(!o.green||!o.permit){round(o.x-4,387,98,9,3,'#e8b7b4');for(let x=o.x;x<o.x+90;x+=24)round(x,387,12,9,1,'#fff0de');}}round(o.x+72,401,24,40,5,'#465f80');g.fillStyle='#86573e';g.beginPath();g.arc(o.x+84,389,12,0,7);g.fill();round(o.x+68,373,31,8,3,'#314b71');round(o.x+76,367,18,9,3,'#314b71');round(o.x+74,437,8,23,2,'#354966');round(o.x+87,437,8,23,2,'#354966');text(F.police.name,o.x+48,350,12,'#fff1da','center');}if(world.sister){const sister=world.sister,peace=sister.passed;if(!peace){round(615,0,8,460,3,'#aa6e9460');for(let y=45;y<440;y+=70)heart(619,y,22,'#c77eaa');}drawCharacter('gcinile',peace?'peace':'normal',sister.x+(peace?62:0)-4,sister.y-3,56,89);text(F.sister.name,sister.x+24+(peace?62:0),sister.y-14,14,'#7b4f68','center');}for(const e of world.enemies){if(e.y>600)continue;cloud(e.x+e.w/2,e.y+17,.48,saved.level===1?'#9b82a1':'#b9afb4');text('• •',e.x+e.w/2,e.y+17,15,'#5c4852','center');text('⌢',e.x+e.w/2,e.y+27,15,'#5c4852','center');}
round(world.goal-50,286,165,174,12,saved.level===1?'#91627f':'#e9b9a6');g.fillStyle='#be7881';g.beginPath();g.moveTo(world.goal-68,300);g.lineTo(world.goal+32,236);g.lineTo(world.goal+128,300);g.fill();round(world.goal+18,380,37,80,18,'#936675');heart(world.goal+35,337,34,'#fff0dc');if(saved.level===2){drawCharacter('bongumusa','holding-heart',world.goal-38,369,58,94);text(C.boyfriendName,world.goal-10,357,14,'#775459','center');text(F.journey.arrival,world.goal+30,280,14,'#fff3db','center');}else{text(F.journey.next[saved.level],world.goal+32,356,13,'#775459','center');}
drawBenoni(true);if(player.invincible===0||Math.floor(time*12)%2||time<boostUntil){if(time<boostUntil){g.strokeStyle='#ffdf8a';g.lineWidth=3;g.beginPath();g.ellipse(player.x+21,player.y+39,33,51,0,0,7);g.stroke();}const bounce=player.grounded&&player.vx?Math.sin(time*20)*2:0;text('P1',player.x+21,player.y-13,10,'#fff4cc','center');drawCharacter('bongeka',player.vy<-100?'run1':Math.abs(player.vx)>10?(Math.floor(time*9)%2?'run1':'run2'):'smiling',player.x-3,player.y-3+bounce,49,80,player.facing);}
for(const p of particles){g.globalAlpha=Math.min(1,p.life);if(p.label){g.strokeStyle='#5e3d60';g.lineWidth=3;g.font='bold 17px Trebuchet MS';g.strokeText(p.label,p.x,p.y);text(p.label,p.x,p.y,17,p.color);}else heart(p.x,p.y,10,p.color);}g.globalAlpha=1;g.restore();
}

function ending(){stop();canvas=null;$('#app').classList.remove('playing');const U=F.gameUI;$('#app').innerHTML=`<section class="ending"><span class="quest-badge">${esc(U.win)} · ${esc(F.journey.from)} → ${esc(F.journey.to)}</span><h1>${esc(U.winTitle)}</h1><div class="reunion-pair">${portrait('bongeka','holding-heart')}${portrait('bongumusa','celebrating')}</div><div class="reunion-score">LOVE 999% ♥</div><p>${esc(U.winLine)}</p><p>${esc(F.reunion)}</p><div class="passport-stamps"><span>✓ ${esc(F.journey.from)}</span><span>✓ ${esc(F.journey.via)}</span><span>✓ ${esc(F.journey.to)}</span></div><p class="tiny">${saved.hearts} HEARTS · ${saved.letters.length} SECRET NOTES · YOU DID THAT.</p><button class="primary" id="more">A MESSAGE FROM YOUR MAN ♥</button><div id="final-note" hidden><h2>I love you, ${esc(C.girlfriendName)}.</h2><p class="letter-copy">${esc(C.finalMessage)}</p><div class="media" id="media"></div><button class="secret" id="secret" aria-label="Hidden heart">♡</button></div><br><button class="subtle" id="reset">PLAY AGAIN ↻</button></section>`;refreshPortraits();$('#more').onclick=()=>{tone('secret');$('#final-note').hidden=false;$('#more').hidden=true;loadMedia();};$('#reset').onclick=()=>{if(confirm(U.freshConfirm)){saved=clean();save();home();}};$('#secret').onclick=()=>{tone('win');if(!saved.eggs.includes('secret'))saved.eggs.push('secret');save();toast(C.reactions.secret);};}
async function loadMedia(){const host=$('#media');for(const [title,path,type]of [['Our photo',C.couplePhoto,'img'],['A video for you',C.video,'video'],['My voice, for you',C.voiceNote,'audio']]){const el=document.createElement('div');el.textContent=title+' · coming soon ♥';host.append(el);try{const r=await fetch(path,{method:'HEAD'});if(r.ok&&!r.headers.get('content-type')?.includes('text/html')){if(!host.isConnected)return;const m=document.createElement(type);m.src=path;if(type==='img')m.alt='Our favourite memory';else m.controls=true;m.onerror=()=>el.textContent=title+' · coming soon ♥';el.textContent=title;el.append(m);}}catch{}}const el=document.createElement('div');el.textContent='Our playlist · coming soon ♥';if(/^https?:\/\//i.test(C.playlistURL)){const a=document.createElement('a');a.href=C.playlistURL;a.textContent='Our playlist ♥';a.target='_blank';a.rel='noopener';el.replaceChildren(a);}host.append(el);}
let soundContext=null,soundEnabled=false;
function tone(kind){if(!soundEnabled||!soundContext)return;try{const patterns={jump:[280,520],coin:[700,1050],menu:[330,440],pop:[190,100],secret:[440,660,880],win:[440,550,660,880]};const notes=patterns[kind]||patterns.menu;notes.forEach((freq,i)=>{const osc=soundContext.createOscillator(),gain=soundContext.createGain(),t=soundContext.currentTime+i*.085;osc.type='triangle';osc.frequency.setValueAtTime(freq,t);gain.gain.setValueAtTime(.0001,t);gain.gain.exponentialRampToValueAtTime(.055,t+.008);gain.gain.exponentialRampToValueAtTime(.0001,t+.13);osc.connect(gain);gain.connect(soundContext.destination);osc.start(t);osc.stop(t+.15);});}catch{}}
if($('#sfx'))$('#sfx').onclick=async()=>{try{if(!soundContext){const AudioEngine=window.AudioContext||window.webkitAudioContext;if(!AudioEngine){toast('Sound effects aren’t supported in this browser. The quest still works.');return;}soundContext=new AudioEngine();}await soundContext.resume();soundEnabled=!soundEnabled;$('#sfx').textContent=soundEnabled?'SFX ON':'SFX OFF';$('#sfx').setAttribute('aria-pressed',String(soundEnabled));if(soundEnabled)tone('menu');}catch{toast('Tap again to enable sound effects.');}};
const audio=new Audio(C.music);audio.loop=true;$('#music').onclick=async()=>{if(!audio.paused){audio.pause();$('#music').textContent='♫ MUSIC OFF';$('#music').setAttribute('aria-pressed','false');}else try{await audio.play();$('#music').textContent='♫ MUSIC ON';$('#music').setAttribute('aria-pressed','true');}catch{toast('Add our soundtrack to bring this world to life ♥');}};audio.onerror=()=>{$('#music').textContent='♫ MUSIC OFF';$('#music').setAttribute('aria-pressed','false');};
window.addEventListener('keydown',e=>{if(!canvas?.isConnected||$('#modal').open)return;const k=e.key.length===1?e.key.toLowerCase():e.key;if(['ArrowLeft','ArrowRight','ArrowUp',' ','a','d','w'].includes(k)&&!['BUTTON','A','INPUT'].includes(e.target.tagName)){e.preventDefault();if(!paused){heldKeys.add(k);syncInput();if(['ArrowUp',' ','w'].includes(k)&&!e.repeat)input.jump=true;}}if(k==='p'&&!e.repeat&&!paused)input.peace=true;if(k==='e'&&!e.repeat&&!paused){if(world.benoni&&!world.benoni.passed&&Math.abs(player.x-world.benoni.gate)<115)input.unlock=true;else readLetter();}if(k==='Escape'&&!e.repeat)paused?resume():pause();});window.addEventListener('keyup',e=>{heldKeys.delete(e.key.length===1?e.key.toLowerCase():e.key);syncInput();});window.addEventListener('blur',()=>{if(canvas?.isConnected&&!paused)pause();release();});document.addEventListener('visibilitychange',()=>{if(document.hidden&&canvas?.isConnected&&!paused)pause();});function viewport(){if(document.documentElement?.style?.setProperty)document.documentElement.style.setProperty('--viewport-height',(window.visualViewport?.height||window.innerHeight)+'px');release();resize();}window.addEventListener('resize',viewport);window.visualViewport?.addEventListener('resize',viewport);viewport();window.addEventListener('pagehide',save);home();
})();
