(() => {
'use strict';
const C=window.LOVE_CONFIG,$=s=>document.querySelector(s),key='little-love-adventure-v1';
const fresh=()=>({level:0,quizIndex:0,quizScore:0,quizAnswered:false,catchScore:0,hearts:0,catchRemaining:20,catchDone:false,love:20,opened:[],puzzleDone:false,tiles:[4,0,7,2,8,1,6,3,5],eggs:[],revealed:false,finalDone:false});
let state;try{state={...fresh(),...JSON.parse(localStorage.getItem(key)||'{}')};}catch{state=fresh();}
state.level=Math.max(0,Math.min(5,Number(state.level)||0));
let timer=null,spawnTimer=null,timeout=null,selection=null,active=false,epoch=0,taps={meter:0,bongeka:0,bongumusa:0};
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function save(){try{localStorage.setItem(key,JSON.stringify(state));}catch{}}
function toast(message){$('#toast').textContent=message;$('#toast').classList.add('show');clearTimeout(timeout);timeout=setTimeout(()=>$('#toast').classList.remove('show'),4000);}
function egg(id,message){if(!state.eggs.includes(id))state.eggs.push(id);save();toast(message);}
function burst(count=45){if(matchMedia('(prefers-reduced-motion: reduce)').matches)count=8;for(let i=0;i<count;i++){const el=document.createElement('span');el.className='particle';el.textContent=['♥','♡','✦','·'][i%4];el.style.cssText=`left:${Math.random()*100}%;color:${['#c85b71','#ddb76d','#e69ba8'][i%3]};font-size:${12+Math.random()*20}px;animation-delay:${Math.random()*.6}s;`;$('#particles').append(el);setTimeout(()=>el.remove(),4000);}}
function char(person,pose='smiling'){return `<button class="character" data-person="${person}" aria-label="${esc(C[person==='bongeka'?'girlfriendName':'boyfriendName'])}"><img src="${esc(C.characters[person]+pose+'.svg')}" alt="Illustrated ${esc(C[person==='bongeka'?'girlfriendName':'boyfriendName'])}"></button>`;}
function couple(pose='holding-heart'){return `<div class="hero-art">${char('bongumusa',pose)}${char('bongeka',pose)}<span class="heart-doodle" aria-hidden="true">♡</span></div>`;}
function card(body){$('#screen').innerHTML=`<section class="card">${body}</section>`;}
function next(label='Continue our adventure →'){return `<button class="primary" id="next">${label}</button>`;}
function go(level){stop();state.level=level;state.love=[20,20,40,60,80,95][level];save();render();window.scrollTo({top:0,behavior:'smooth'});}
function stop(){clearInterval(timer);clearInterval(spawnTimer);active=false;epoch++;}
function update(){ $('#names').textContent=`${C.girlfriendName} ❤️ ${C.boyfriendName}`;$('#percentage').textContent=state.love+'%';$('#fill').style.width=Math.min(100,state.love)+'%';$('#steps').innerHTML=Array.from({length:5},(_,i)=>`<span class="${state.level>i+1?'done':state.level===i+1?'active':''}" aria-label="Level ${i+1}${state.level>i+1?' completed':''}" ${state.level===i+1?'aria-current="step"':''}>${state.level>i+1?'✓':i+1}</span>`).join('');}
function render(){update();if(state.level===0){card(`<div class="eyebrow">A little game. A whole lot of love.</div><h1>${esc(C.girlfriendName)} &amp;<br>${esc(C.boyfriendName)} <em>♡</em></h1><p style="font-family:Georgia;font-style:italic;font-size:19px">Our Little Love Adventure</p>${couple()}<p class="intro">${esc(C.openingMessage)}</p><br>${next('Start Our Adventure ♡')}<p class="caption">5 LITTLE CHAPTERS · ONE BIG SURPRISE</p>`);$('#next').onclick=()=>go(1);}
else if(state.level===1)quiz();else if(state.level===2)catchScreen();else if(state.level===3)puzzle();else if(state.level===4)letters();else final();}
function quiz(){const q=C.quizQuestions[state.quizIndex];if(!q){card(`<div class="eyebrow">Chapter 01 complete</div><h2>You know our little world ♡</h2>${couple('celebrating')}<p>${state.quizScore} of ${C.quizQuestions.length} answers. Every answer brings us closer.</p>${next()}`);$('#next').onclick=()=>go(2);return;}
card(`<div class="eyebrow">Chapter 01 · How well do you know us?</div><div class="progress-label">QUESTION ${state.quizIndex+1} / ${C.quizQuestions.length}</div><h2>${esc(q.question)}</h2><div class="mini-art" id="quiz-art">${char('bongeka','thinking')}${char('bongumusa')}</div><div class="options">${q.options.map((o,i)=>`<button class="option" data-answer="${i}" ${state.quizAnswered?'disabled':''}><span>${String.fromCharCode(65+i)}</span>${esc(o)}</button>`).join('')}</div><div class="feedback" id="feedback" role="status">${state.quizAnswered?'Your answer is saved. Let’s keep going.':''}</div>${state.quizAnswered?next('Next question →'):''}`);
document.querySelectorAll('[data-answer]').forEach(b=>b.onclick=()=>{if(state.quizAnswered)return;state.quizAnswered=true;const correct=Number(b.dataset.answer)===q.answer;if(correct)state.quizScore++;save();document.querySelectorAll('[data-answer]').forEach(x=>x.disabled=true);b.classList.add(correct?'correct':'wrong');$('#feedback').textContent=correct?C.reactions.correct:C.reactions.wrong;$('#quiz-art').innerHTML=char('bongeka',correct?'smiling':'laughing')+char('bongumusa',correct?'celebrating':'surprised');if(correct)burst(12);$('#feedback').insertAdjacentHTML('afterend',next('Next question →'));bindQuizNext();});bindQuizNext();}
function bindQuizNext(){if($('#next'))$('#next').onclick=()=>{state.quizIndex++;state.quizAnswered=false;save();quiz();};}
function catchScreen(){if(state.catchDone){card(`<div class="eyebrow">Chapter 02 complete</div><h2>A heart worth catching</h2>${couple('celebrating')}<p class="final-copy">${esc(C.reactions.catch)}</p><p>${state.hearts} hearts collected · ${state.catchScore} points</p>${next()}`);$('#next').onclick=()=>go(3);return;}
card(`<div class="eyebrow">Chapter 02 · Catch my love</div><h2>A little <em>heart chase.</em></h2><p>Tap the hearts. Watch out for a little mischief.</p><div class="stats"><div><strong id="time">${state.catchRemaining}</strong><span>seconds</span></div><div><strong id="score">${state.catchScore}</strong><span>points</span></div><div><strong id="hearts">${state.hearts}</strong><span>hearts</span></div></div><div class="arena" id="arena">${char('bongumusa','holding-heart')}</div><br><button class="primary" id="start-catch">${state.catchRemaining<20?'Resume catching':'Ready, set, love! ♡'}</button>`);
$('#start-catch').onclick=()=>{if(active)return;active=true;$('#start-catch').disabled=true;$('#start-catch').textContent='Catch those hearts!';spawn();spawnTimer=setInterval(spawn,650);timer=setInterval(()=>{state.catchRemaining--;save();$('#time').textContent=state.catchRemaining;if(state.catchRemaining<=0){stop();state.catchDone=true;save();burst();catchScreen();}},1000);};}
function spawn(){const arena=$('#arena');if(!arena)return;const b=document.createElement('button'),good=Math.random()<.76;b.className='target';b.textContent=good?'❤️':['💔','😂','💩'][Math.floor(Math.random()*3)];b.setAttribute('aria-label',good?'Catch heart':'Mischief');b.style.left=(8+Math.random()*Math.max(0,arena.clientWidth-70))+'px';b.style.top=(10+Math.random()*(arena.clientHeight-80))+'px';b.onpointerdown=e=>{if(e.pointerType!=='mouse'){e.preventDefault();collect();}};b.onclick=collect;let used=false;function collect(){if(used||!active)return;used=true;if(good){state.catchScore+=10;state.hearts++;}else{state.catchScore=Math.max(0,state.catchScore-5);toast('A little mischief! Love still wins 😂');}save();$('#score').textContent=state.catchScore;$('#hearts').textContent=state.hearts;b.remove();}arena.append(b);setTimeout(()=>b.remove(),2000);}
let puzzleURL='assets/images/memory-placeholder.svg';const photo=new Image();photo.onload=()=>{puzzleURL=C.puzzlePhoto;if(state.level===3)puzzle();};photo.src=C.puzzlePhoto;
function puzzle(){if(state.puzzleDone){card(`<div class="eyebrow">Chapter 03 complete</div><h2>Every piece. <em>Us.</em></h2>${couple('celebrating')}<p>${esc(C.reactions.puzzle)}</p>${next()}`);$('#next').onclick=()=>go(4);return;}
card(`<div class="eyebrow">Chapter 03 · Our memory</div><h2>We belong <em>together.</em></h2><p>Tap two pieces to swap them into place.</p><div class="puzzle">${state.tiles.map((n,i)=>`<button class="tile" data-tile="${i}" aria-label="Piece ${n+1}, position ${i+1}" style="background-image:url('${esc(puzzleURL)}');background-position:${(n%3)*50}% ${Math.floor(n/3)*50}%"><span>${n+1}</span></button>`).join('')}</div><p class="help">Put the pieces in order, 1–9, from left to right.</p><button class="secondary" id="hint">A little help ♡</button>`);document.querySelectorAll('[data-tile]').forEach(b=>b.onclick=()=>{const i=Number(b.dataset.tile);if(selection===null){selection=i;b.classList.add('selected');}else{[state.tiles[i],state.tiles[selection]]=[state.tiles[selection],state.tiles[i]];selection=null;checkPuzzle();}});$('#hint').onclick=()=>{const i=state.tiles.findIndex((n,i)=>n!==i);if(i>=0){const j=state.tiles.indexOf(i);[state.tiles[i],state.tiles[j]]=[state.tiles[j],state.tiles[i]];}selection=null;checkPuzzle();};}
function checkPuzzle(){if(state.tiles.every((n,i)=>n===i)){state.puzzleDone=true;burst();}save();puzzle();}
function letters(){card(`<div class="eyebrow">Chapter 04 · Open when...</div><h2>A little love, <em>on standby.</em></h2><p>For the moments I wish I could be there.</p><div class="mini-art">${char('bongeka','thinking')}</div><div class="envelopes">${C.loveLetters.map((l,i)=>`<button class="envelope ${state.opened.includes(i)?'opened':''}" data-letter="${i}"><span class="icon">${state.opened.includes(i)?'💌':'✉'}</span><span><strong>${esc(l.short)}</strong><small>${state.opened.includes(i)?'Opened · read again':'A letter from your favourite person'}</small></span></button>`).join('')}</div><p class="help">${state.opened.length} of ${C.loveLetters.length} letters opened</p>${state.opened.length===C.loveLetters.length?next('Your surprise is waiting →'):''}`);document.querySelectorAll('[data-letter]').forEach(b=>b.onclick=()=>{const i=Number(b.dataset.letter);if(!state.opened.includes(i))state.opened.push(i);save();letters();$('#letter-content').innerHTML=`<div class="mini-art">${char('bongumusa','romantic')}</div><h2>${esc(C.loveLetters[i].title)}</h2><p class="final-copy">${esc(C.loveLetters[i].message)}</p>`;$('#letter').showModal();});if($('#next'))$('#next').onclick=()=>go(5);}
function final(){if(!state.finalDone){card(`<div class="eyebrow">The final chapter · Just for you</div><h2>A surprise, <em>with your name on it.</em></h2>${couple()}<div class="gift">🎁</div><p id="suspense">Some things are worth waiting for.</p><button class="primary" id="unlock">Unlock my surprise ♡</button>`);$('#unlock').onclick=async()=>{const token=epoch;$('#unlock').disabled=true;for(const line of C.suspense){if(token!==epoch)return;$('#suspense').textContent=line;await new Promise(r=>setTimeout(r,1400));}if(token!==epoch)return;state.finalDone=true;state.love=999;save();burst(90);final();update();};return;}
state.love=999;update();card(`<div class="eyebrow">Love level: beyond the limit</div><h1>${state.revealed?'I choose you.<br><em>Again and again.</em>':'YOU WON! <em>♡</em>'}</h1>${couple('celebrating')}${state.revealed?`<p class="intro final-copy">${esc(C.finalMessage)}</p><div class="media-grid" id="media"></div><button class="secret" id="secret" aria-label="Little hidden heart">♡</button>`:`<p class="final-copy">${esc(C.winMessage)}</p><h2>I love you, ${esc(C.girlfriendName)}. ♡</h2><p>${esc(C.loveMessage)}</p><button class="primary" id="more">One more thing... 👀</button>`}<br><button class="secondary" id="reset">Play Again ❤️</button>`);if($('#more'))$('#more').onclick=()=>{state.revealed=true;save();burst();final();};if($('#secret'))$('#secret').onclick=()=>{egg('secret',C.reactions.secret);burst();};$('#reset').onclick=()=>{if(confirm('Start our adventure again? Your saved game progress will be cleared.')){stop();state=fresh();save();render();}};if(state.revealed)loadMedia();}
async function exists(path){if(!path)return false;try{const r=await fetch(path,{method:'HEAD'});return r.ok&&!r.headers.get('content-type')?.includes('text/html');}catch{return false;}}
async function loadMedia(){const host=$('#media');const items=[['Our couple photo',C.couplePhoto,'img'],['A little video',C.video,'video'],['My voice, for you',C.voiceNote,'audio']];for(const [title,path,type]of items){const el=document.createElement('div');el.className='media';el.textContent=title+' · coming soon ♡';host.append(el);if(await exists(path)){if(!host.isConnected)return;const media=document.createElement(type);media.src=path;if(type==='img')media.alt='Our favourite memory';else media.controls=true;media.onerror=()=>{el.textContent=title+' · coming soon ♡';};el.textContent=title;el.append(media);}}const el=document.createElement('div');el.className='media';el.textContent='Our playlist · coming soon ♡';if(/^https?:\/\//i.test(C.playlistURL)){const a=document.createElement('a');a.href=C.playlistURL;a.target='_blank';a.rel='noopener';a.textContent='Listen to our playlist ♡';el.replaceChildren(a);}host.append(el);}
const audio=new Audio(C.music);audio.loop=true;let musicOn=false;$('#music').onclick=async()=>{if(musicOn){audio.pause();musicOn=false;}else{try{await audio.play();musicOn=true;}catch{toast('Our soundtrack is coming soon ♡');}}$('#music span').textContent=musicOn?'Music on':'Music off';$('#music').setAttribute('aria-pressed',String(musicOn));};audio.onerror=()=>{musicOn=false;$('#music span').textContent='Music off';};
$('#meter').onclick=()=>{taps.meter++;if(taps.meter%5===0)egg('meter',C.reactions.meter);else if(state.love===999){toast(C.reactions.overflow);burst(15);document.querySelectorAll('.character img').forEach(img=>{const old=img.src;img.src=old.replace(/[^/]+\.svg$/,'laughing.svg');setTimeout(()=>{if(img.isConnected)img.src=old;},1800);});}};
function tapPerson(person){taps[person]++;if(taps[person]%5===0)egg(person,C.reactions[person==='bongeka'?'girl':'boy']);}
$('#names').onclick=()=>tapPerson('bongumusa');document.addEventListener('click',e=>{const b=e.target.closest('[data-person]');if(b)tapPerson(b.dataset.person);});$('#close-letter').onclick=()=>$('#letter').close();
const code=['ArrowUp','ArrowUp','ArrowDown','ArrowDown','ArrowLeft','ArrowRight','ArrowLeft','ArrowRight','b','a'];let codeIndex=0;document.addEventListener('keydown',e=>{const k=e.key.length===1?e.key.toLowerCase():e.key;if(k===code[codeIndex]){codeIndex++;if(codeIndex===code.length){codeIndex=0;egg('konami','Secret love explosion unlocked ♡');burst(100);}}else codeIndex=k===code[0]?1:0;});
document.addEventListener('visibilitychange',()=>{if(document.hidden&&active){stop();save();catchScreen();}});window.addEventListener('pagehide',save);render();
})();
