const fs=require('fs'),vm=require('vm'),assert=require('assert');
class El{constructor(id=''){this.id=id;this.dataset={};this.style={};this.classList={add(){},remove(){}};this.isConnected=true;this.clientWidth=350;this.clientHeight=320;}set innerHTML(v){this.html=v;for(const id of v.matchAll(/id="([^"]*)"/g))elements[id[1]]=new El(id[1]);for(const m of v.matchAll(/<button\b([^>]*)>([\s\S]*?)<\/button>/g)){const b=new El();b.textContent=m[2];for(const a of m[1].matchAll(/(id|data-[\w-]+)="([^"]*)"/g)){if(a[1]==='id'){b.id=a[2];elements[b.id]=b;}else b.dataset[a[1].slice(5)]=a[2];}buttons.push(b);}}get innerHTML(){return this.html||'';}insertAdjacentHTML(_,v){this.innerHTML=v;}append(){}remove(){}setAttribute(){}showModal(){this.open=true;}close(){this.open=false;}}
let elements={},buttons=[],stored={},events={},intervals=[];for(const id of ['screen','meter','names','percentage','fill','steps','toast','particles','music','letter','letter-content','close-letter'])elements[id]=new El(id);elements['music span']=new El();
const document={querySelector(s){return elements[s.slice(1)]||null;},querySelectorAll(s){if(s==='[data-answer]')return buttons.filter(b=>'answer'in b.dataset).slice(-4);if(s==='[data-tile]')return buttons.filter(b=>'tile'in b.dataset).slice(-9);if(s==='[data-letter]')return buttons.filter(b=>'letter'in b.dataset).slice(-3);return[];},createElement(){return new El();},addEventListener(n,f){events[n]=f;}};
const ctx={window:{scrollTo(){},addEventListener(){}},document,localStorage:{getItem:k=>stored[k]||null,setItem:(k,v)=>stored[k]=v},matchMedia:()=>({matches:true}),Image:class{},Audio:class{pause(){}play(){return Promise.reject();}},fetch:async()=>({ok:false}),confirm:()=>true,setTimeout:f=>{return 1;},clearTimeout(){},setInterval:f=>{intervals.push(f);return intervals.length;},clearInterval(){},console};vm.createContext(ctx);vm.runInContext(fs.readFileSync('js/config.js','utf8'),ctx);vm.runInContext(fs.readFileSync('js/classic.js','utf8'),ctx);
const state=()=>JSON.parse(stored['little-love-adventure-v1']);const click=id=>{assert(elements[id]?.onclick,id+' should be reachable');elements[id].onclick();};
click('next');assert.equal(state().level,1);for(let i=0;i<7;i++){document.querySelectorAll('[data-answer]')[0].onclick();click('next');}click('next');assert.equal(state().level,2);click('start-catch');const tick=intervals[intervals.length-1];for(let i=0;i<20;i++)tick();assert(state().catchDone);click('next');assert.equal(state().level,3);for(let i=0;i<9&&!state().puzzleDone;i++)click('hint');assert(state().puzzleDone);click('next');assert.equal(state().level,4);for(let i=0;i<3;i++){document.querySelectorAll('[data-letter]')[i].onclick();click('close-letter');}assert.equal(state().opened.length,3);click('next');assert.equal(state().level,5);assert(elements.unlock.onclick);let saved=state();saved.finalDone=true;saved.love=999;stored['little-love-adventure-v1']=JSON.stringify(saved);vm.runInContext(fs.readFileSync('js/classic.js','utf8'),ctx);click('more');click('secret');assert(state().eggs.includes('secret'));for(let i=0;i<5;i++)click('meter');assert(state().eggs.includes('meter'));for(let i=0;i<5;i++)click('names');assert(state().eggs.includes('bongumusa'));for(const key of ['ArrowUp','ArrowUp','ArrowDown','ArrowDown','ArrowLeft','ArrowRight','ArrowLeft','ArrowRight','b','a'])events.keydown({key});assert(state().eggs.includes('konami'));click('reset');assert.equal(state().level,0);console.log('PASS: quiz, timed game, puzzle, letters, final resume, reveal, meter/name/secret/Konami eggs, reset and storage.');


(async()=>{saved={...state(),level:5,finalDone:false,love:95};stored['little-love-adventure-v1']=JSON.stringify(saved);ctx.setTimeout=f=>{f();return 1;};vm.runInContext(fs.readFileSync('js/classic.js','utf8'),ctx);await elements.unlock.onclick();assert(state().finalDone);assert.equal(state().love,999);for(let i=0;i<5;i++)events.click({target:{closest:()=>({dataset:{person:'bongeka'}})}});assert(state().eggs.includes('bongeka'));console.log('PASS: suspense unlock reaches 999% and Bongeka character Easter egg.');})().catch(e=>{console.error(e);process.exitCode=1;});

