const {chromium}=require('../.qa/node_modules/playwright');const fs=require('fs');const assert=require('assert');
(async()=>{const browser=await chromium.launch({executablePath:'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe',headless:true});fs.mkdirSync('qa/artifacts',{recursive:true});let errors=[];
for(const [w,h] of [[320,568],[360,640],[375,667],[390,844],[412,915],[667,375],[844,390]]){const context=await browser.newContext({viewport:{width:w,height:h},isMobile:true,hasTouch:true});const page=await context.newPage();page.on('pageerror',e=>errors.push(e.message));await page.goto('http://127.0.0.1:8000');await page.waitForFunction(()=>document.querySelector('[data-character]')?.src.startsWith('data:image/png'));await page.locator('#start').click();await page.locator('#ready').scrollIntoViewIfNeeded();await page.locator('#ready').click();await page.waitForTimeout(100);const check=async()=>{for(const sel of ['[data-move="left"]','[data-move="right"]','#jump','#hint','#home','#pause']){const r=await page.locator(sel).boundingBox();assert(r&&r.x>=0&&r.y>=0&&r.x+r.width<=w+1&&r.y+r.height<=h+1,`${w}x${h} ${sel} outside screen ${JSON.stringify(r)}`);}assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'horizontal overflow');};await check();await page.screenshot({path:`qa/artifacts/mobile-${w}-${h}.png`});await page.locator('#hint').tap();assert(await page.locator('#modal').isVisible());await page.locator('#modal-close').tap();await page.setViewportSize({width:h,height:w});await page.waitForTimeout(150);await page.setViewportSize({width:w,height:h});await page.waitForTimeout(200);await check();
for(const [level,checkpoint,action] of [[0,500,'#peace'],[2,1220,'#unlock']]){await page.addInitScript(v=>localStorage.setItem('love-platform-v2',JSON.stringify(v)),{level,checkpoint,benoniKeys:[0,1,2]});await page.reload();await page.locator('#start').tap();await page.locator('#ready').tap();await page.waitForTimeout(250);await check();const r=await page.locator(action).boundingBox();assert(r&&r.y+r.height<=h,`${action} invisible`);await page.locator(action).tap();}
const cdp=await context.newCDPSession(page);const right=await page.locator('[data-move="right"]').boundingBox(),jump=await page.locator('#jump').boundingBox();await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:right.x+20,y:right.y+20,id:1}]});await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:right.x+20,y:right.y+20,id:1},{x:jump.x+20,y:jump.y+20,id:2}]});await page.waitForTimeout(150);assert(await page.locator('[data-move="right"]').evaluate(e=>e.classList.contains('held')));await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});assert(!(await page.locator('[data-move="right"]').evaluate(e=>e.classList.contains('held'))));await context.close();console.log(`PASS ${w}x${h}: controls, clues, boss/escape actions, rotation and multitouch`);}
assert.deepEqual(errors,[]);await browser.close();})().catch(e=>{console.error(e);process.exit(1)});



